version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_strong_password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P Your_strong_password123! -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./CalendarAPI
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=WorkshopCalendar;User=sa;Password=Your_strong_password123!;
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - appnet

  frontend:
    build:
      context: ./CalendarFrontEnd
    depends_on:
      - api
    ports:
      - "3000:80"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge 