name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      working-directory: ./CalendarAPI.Tests/
      run: dotnet restore

    - name: Build
      working-directory: ./CalendarAPI.Tests/
      run: dotnet build --no-restore

    - name: Test
      working-directory: ./CalendarAPI.Tests/
      run: dotnet test --no-build --verbosity normal 