name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - name: Restore unit test dependencies
        working-directory: ./CalendarAPI.Tests/
        run: dotnet restore

      - name: Build unit tests
        working-directory: ./CalendarAPI.Tests/
        run: dotnet build --no-restore

      - name: Run unit tests
        working-directory: ./CalendarAPI.Tests/
        run: dotnet test --no-build --verbosity normal

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - name: Restore integration test dependencies
        working-directory: ./CalendarAPI.IntegrationTests/
        run: dotnet restore

      - name: Build integration tests
        working-directory: ./CalendarAPI.IntegrationTests/
        run: dotnet build --no-restore

      - name: Run integration tests
        working-directory: ./CalendarAPI.IntegrationTests/
        run: dotnet test --no-build --verbosity normal 